#!/usr/bin/env bash

set -euo pipefail

source "$(cd "$(dirname "$0")" && pwd)/_common.sh"

require_cmd git
require_cmd python3
parse_platform_args "$@"
prepare_build_dirs
ensure_generated_workspace

VERSION="$(read_lock_value "version")"
OUTPUT_DIR="${PATCHES_ROOT}/${PLATFORM}/${VERSION}"
mkdir -p "${OUTPUT_DIR}"

BASELINE_ROOT="$(mktemp -d "${GENERATED_ROOT}/.baseline.XXXXXX")"
BASELINE_SRC="${BASELINE_ROOT}/LMCache"
CURRENT_COPY_ROOT="$(mktemp -d "${GENERATED_ROOT}/.current.XXXXXX")"
CURRENT_COPY="${CURRENT_COPY_ROOT}/LMCache"
RAW_DIFF="${BASELINE_ROOT}/raw.diff"
OUTPUT_PATCH="${OUTPUT_DIR}/0000-autogenerated.patch"

cleanup() {
    rm -rf "${BASELINE_ROOT}"
    rm -rf "${CURRENT_COPY_ROOT}"
}
trap cleanup EXIT

log "Preparing pristine baseline from tarball"
extract_locked_tarball_to "${BASELINE_ROOT}"
while IFS= read -r layer; do
    layer_overlay_dir="$(overlay_dir_for_layer "${layer}")"
    [[ -d "${layer_overlay_dir}" ]] || continue
    for overlay_entry in "${layer_overlay_dir}"/*; do
        entry_name="$(basename "${overlay_entry}")"
        if [[ "${entry_name}" == "README.md" ]] || [[ "${entry_name}" == "__pycache__" ]]; then
            continue
        fi
        cp -a "${overlay_entry}" "${BASELINE_SRC}/"
    done
done < <(overlay_layers_for_platform)

if [[ "${PLATFORM}" == "ascend" ]]; then
    GENERATED_SRC_DIR="${BASELINE_SRC}" materialize_kvcache_ops_into_workspace
fi

log "Copying current generated workspace"
cp -a "${GENERATED_SRC_DIR}" "${CURRENT_COPY}"
rm -f "${CURRENT_COPY}/.wings_patchset_applied" "${CURRENT_COPY}"/.wings_patchset_applied.*

log "Generating no-index diff against current generated workspace"
set +e
git diff --no-index --src-prefix=a/ --dst-prefix=b/ "${BASELINE_SRC}" "${CURRENT_COPY}" > "${RAW_DIFF}"
DIFF_EXIT=$?
set -e

if [[ "${DIFF_EXIT}" -eq 0 ]]; then
    warn "No diff detected; generated workspace matches baseline+overlay"
    : > "${OUTPUT_PATCH}"
    exit 0
fi

python3 - "${RAW_DIFF}" "${BASELINE_SRC}" "${CURRENT_COPY}" "${OUTPUT_PATCH}" <<'PY'
from pathlib import Path
import sys

raw_diff = Path(sys.argv[1])
left = Path(sys.argv[2]).as_posix().rstrip("/")
right = Path(sys.argv[3]).as_posix().rstrip("/")
output = Path(sys.argv[4])

text = raw_diff.read_text()
text = text.replace(f"a/{left}/", "a/")
text = text.replace(f"b/{right}/", "b/")
text = text.replace(f" {left}/", " ")
text = text.replace(f" {right}/", " ")
output.write_text(text)
PY

log "Wrote combined autogenerated patch to ${OUTPUT_PATCH}"
warn "The autogenerated patch is a best-effort combined diff. Split it into smaller hook patches before long-term use."
